name: "Python Monorepo CI"
on: [push]
jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        project: [projecta]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Python 3.12"
        uses: "actions/setup-python@v3"
        with:
          python-version: "3.12"

      - name: "Install Depdencies"
        run: |
          cd ${{matrix.project}}
          pip install poetry
          poetry install

      - name: "Run App"
        run: |
          cd ${{matrix.project}}
          poetry run python main.py
